version: 2.1
jobs:
  build:
    docker:
    - image: circleci/node:12
    steps:
    - checkout
    - run:
        name: install dependencies
        command: npm ci
    - run:
        name: test
        command: npm test
    - run:
        name: build
        command: npm run build
    - run:
        name: deploy
        command: |
          git config user.name 'CircleCI'
          git config user.email 'circleci@noemail'
          npm run deploy