version: 2.1
jobs:
  build:
    docker:
    - image: circleci/node:12
    steps:
    - checkout
    - run:
        name: install dependencies
        command: npm ci
    - run:
        name: test
        command: npm test
    - run:
        name: build
        command: npm run build
    - add_ssh_keys:
        fingerprints:
        - "ff:df:07:7c:42:e0:7c:2f:9a:58:11:83:4d:67:01:6b"
    - run:
        name: deploy
        command: |
          git config user.name 'CircleCI'
          git config user.email 'circleci@noemail'
          npm run deploy